version: '3'

services:
  nginx-lyucean:
    image: nginx:latest
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Добавляем конфигурационный файл
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-lyucean.rule=Host(`lyucean.com`)"
      - "traefik.http.routers.nginx-lyucean.entrypoints=web"
      - "traefik.http.services.nginx-lyucean.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    external: true # стандартная для всех на этом сервере