version: '3'
services:
  any:
    image: alpine
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    command: ["sh", "-c", 'echo "ENVIRONMENT=${ENVIRONMENT}"']

  prod:
    image: alpine
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    command: ["sh", "-c", 'echo "Это Прод!"']

  dev:
    image: alpine
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    command: ["sh", "-c", 'echo "Это Дев!"']
    profiles:
      - debug