version: '3.9'

services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./app:/app


  prod:
    image: alpine
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    command: [ "sh", "-c", 'echo "Это Прод!"' ]

  dev:
    image: alpine
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    command: [ "sh", "-c", 'echo "Это Дев!"' ]
    profiles:
      - debug