version: '3.9'

services:
  php-cli:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    depends_on:
      - composer
      - mysql

  composer:
    image: composer
    volumes:
      - .:/app
    working_dir: /app
    command: install

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=your_root_password
    depends_on:
      - mysql
    profiles:
      - debug