version: '3.9'

services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    depends_on:
      - composer

  composer:
    image: composer
    volumes:
      - .:/app
    working_dir: /app
    command: install

  prod:
    image: alpine
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    command: [ "sh", "-c", 'echo "Это Прод!"' ]

  dev:
    image: alpine
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    command: [ "sh", "-c", 'echo "Это Дев!"' ]
    profiles:
      - debug