version: '3.9'

services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    depends_on:
      - composer
      - mysql

  composer:
    image: composer
    volumes:
      - .:/app
    working_dir: /app
    command: install

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=your_database_name
      - MYSQL_USER=your_username
      - MYSQL_PASSWORD=your_password

  prod:
    image: alpine
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    command: [ "sh", "-c", 'echo "Это Прод!"' ]

  dev:
    image: alpine
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    command: [ "sh", "-c", 'echo "Это Дев!"' ]
    profiles:
      - debug
