version: '3'

services:
  reverse-proxy:
    image: traefik:v3.0
    command:
      - "--api.insecure=true" # включим веб-интерфейс
      - "--providers.docker=true" # указывает Traefik слушать докер\
      - "--entrypoints.web.address=:80" # указываем точку входа web
#      - "--providers.docker.exposedbydefault=false" # чтоб не подхватывал автоматом контейнеры
    ports:
      - "80:80" # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api.insecure=true)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Чтобы Traefik мог слушать события Docker
    networks:
      - web
networks:
  web:
    external: true