version: '3'

services:
  reverse-proxy:
    image: traefik:v2.10
    restart: always
    command:
      - "--api.insecure=true" # включим веб-интерфейс
      - "--providers.docker=true" # указывает Traefik слушать докер
      - "--entrypoints.web.address=:80" # указываем точку входа web
      - "--entrypoints.websecure.address=:443" # указываем точку входа websecure
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true" # Указываем метод вызова ACME как HTTP Challenge
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=lyucean@gmail.com" # указываем email для регистрации в Let's Encrypt
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json" # указываем путь для хранения сертификатов
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # The Web UI (enabled by --api.insecure=true)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Чтобы Traefik мог слушать события Docker
      - ./letsencrypt:/letsencrypt # папка с сертификатами
    networks:
      - web
    labels:
      # добавим домен traefik.lyucean.com
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.rule=Host(`traefik.lyucean.com`)
      # TLS настройки
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
      # TLS настройки для дашборда
      - traefik.http.services.traefik-traefik.loadbalancer.server.port=8080
      # middleware для редиректа с http на https
      - traefik.http.middlewares.http-redirect.redirectscheme.scheme=https
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=http-redirect
networks:
  web:
    external: true