version: '3'

services:
  reverse-proxy:
    image: traefik:v2.5.4
    command:
      - "--api.insecure=true" # включим веб-интерфейс
      - "--providers.docker=true" # указывает Traefik слушать докер
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=lyucean@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # The Web UI (enabled by --api.insecure=true)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Чтобы Traefik мог слушать события Docker
      - ./letsencrypt:/letsencrypt # папка с сертификатами
    networks:
      - web
    labels:
      # добавим домен traefik.lyucean.com
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.rule=Host(`traefik.lyucean.com`)
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
      - traefik.http.services.traefik-traefik.loadbalancer.server.port=8080
networks:
  web:
    external: true