version: '3'

services:
  nginx-gypsart:
    image: nginx:latest
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Добавляем конфигурационный файл
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-gypsart.rule=Host(`gypsart.com`)"
      - "traefik.http.routers.nginx-gypsart.entryPoints=web"
      - "traefik.http.services.nginx-gypsart.loadBalancer.server.port=80"
    networks:
      - web

networks:
  web:
    external: true # стандартная для всех на этом сервере