version: '3'
services:
  couchserver:
    image: couchdb
    restart: always
    hostname: couchdb.lyucean.com
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
    volumes:
      - ./dbdata:/opt/couchdb/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.couchserver.rule=Host(`couchdb.lyucean.com`)
      - traefik.http.routers.couchserver.entrypoints=websecure
      - traefik.http.routers.couchserver.tls=true
      - traefik.http.routers.couchserver.tls.certresolver=letsencrypt
      - traefik.http.services.couchserver.loadbalancer.server.port=5984
      - traefik.http.services.couchserver.loadbalancer.server.scheme=http
    networks:
      - web

#  fauxton:
#    image: couchdb
#    restart: always
#    ports:
#      - "8000:8000" # Проброс порта для Fauxton
#    command: bash -c "/opt/couchdb/bin/fauxton"
#    networks:
#      - web

networks:
  web:
    external: true # стандартная для всех на этом сервере
