name: Deploy CouchDB

on:
  push:
    paths:
      - "CouchDB/docker-compose.yml"
      - ".github/workflows/couchdb-deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy docker-compose.yml to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "CouchDB"
          target: "/home/user/"

  publish:
    runs-on: ubuntu-latest
    needs: [deploy]
    env:
      COUCHDB_USER: ${{ secrets.COUCHDB_USER }}
      COUCHDB_PASSWORD: ${{ secrets.COUCHDB_PASSWORD }}
    steps:
      - name: Create web network and start docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker network ls | grep web || docker network create web
            touch .env
            echo "test=test" >> .env
            echo "COUCHDB_USER=$COUCHDB_USER" >> .env
            echo "COUCHDB_PASSWORD=$COUCHDB_PASSWORD" >> .env
            echo "test_secrets=${{ secrets.COUCHDB_PASSWORD }}" >> .env
            cd /home/user/CouchDB
            docker-compose pull
            docker-compose up -d
            docker ps

  test:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - name: Check website
        uses: wei/curl@v1
        with:
          args:  https://couchdb.lyucean.com:5984/_utils/
        id: response
      - name: Check response code
        run: |
          if [ ${{ steps.response.outputs.stdout }} -ne 200 ]; then
            echo "CouchDB is not available"
            exit 1
          else
            echo "CouchDB is available"
          fi