name: Deploy Traefik Compose

on:
  push:
    paths:
      - "Traefik/docker-compose.yml"
      - ".github/workflows/traefik-deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy docker-compose.yml to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "Traefik"
          target: "/home/user/"

  publish:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Create web network and start docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker network ls | grep web || docker network create web
            cd /home/user/Traefik
            docker-compose pull
            docker-compose up -d
            docker ps

  test:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - name: Check website
        uses: wei/curl@v1
        with:
          args: -s -o /dev/null -w "%{http_code}" https://${{ secrets.HOST }}:8080/dashboard/
        id: response
      - name: Check response code
        run: |
          if [ ${{ steps.response.outputs.stdout }} -ne 200 ]; then
            echo "Website is not available"
            exit 1
          else
            echo "Website is available"
          fi