name: Deploy Traefik Compose

on:
  push:
    paths:
      - "notes/Traefik/docker-compose.yml"
      - ".github/workflows/traefik-deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy docker-compose file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "notes/Traefik/docker-compose.yml"
          target: "/home/user/traefik/docker-compose.yml"

      - name: Create traefik directory
        run: |
          mkdir -p /home/user/traefik

      - name: Create web network if not exists
        run: |
          if ! docker network inspect web &> /dev/null; then docker network create web; fi

      - name: Deploy docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/user/traefik
            docker-compose pull
            docker-compose up -d